[project]
name = "sql-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiocache>=0.12.3",
    "asyncpg>=0.31.0",
    "groq>=1.6.0",
    "loguru>=0.7.3",
    "pydantic-settings>=2.15.0",
    "sqlglot>=30.17.0",
]
